//
//  Iconic.swift
//  JustIconFont
//
//  Created by YZF on 2019/4/23.
//

import Foundation


extension Iconic: IconFontEnumType {
    
    public var name: String {
        return "Iconic"
    }
    
}


/// Iconic v1.1.1
///
/// An open source icon set with 223 marks in SVG, webfont and raster formats.
///
/// https://useiconic.com/open
public enum Iconic: String {
    case accountLogin = "\u{eaa5}"
    case accountLogout = "\u{eaa8}"
    case actionRedo = "\u{eaa6}"
    case actionUndo = "\u{eaa7}"
    case alignCenter = "\u{eaaa}"
    case alignLeft = "\u{eaa9}"
    case alignRight = "\u{eaab}"
    case aperture = "\u{eaac}"
    case arrowBottom = "\u{eaae}"
    case arrowCircleBottom = "\u{eaaf}"
    case arrowCircleLeft = "\u{eab0}"
    case arrowCircleRight = "\u{eaad}"
    case arrowCircleTop = "\u{eab1}"
    case arrowLeft = "\u{eab3}"
    case arrowRight = "\u{eab2}"
    case arrowThickBottom = "\u{eab4}"
    case arrowThickLeft = "\u{eab5}"
    case arrowThickRight = "\u{eab7}"
    case arrowThickTop = "\u{eab8}"
    case arrowTop = "\u{eab9}"
    case audio = "\u{eaba}"
    case audioSpectrum = "\u{eab6}"
    case badge = "\u{eabd}"
    case ban = "\u{eabb}"
    case barChart = "\u{eabc}"
    case basket = "\u{eabe}"
    case batteryEmpty = "\u{eac2}"
    case batteryFull = "\u{eabf}"
    case beaker = "\u{eac0}"
    case bell = "\u{eac1}"
    case bluetooth = "\u{eac3}"
    case bold = "\u{eac7}"
    case bolt = "\u{eac4}"
    case book = "\u{eac6}"
    case bookmark = "\u{eac5}"
    case box = "\u{eac8}"
    case briefcase = "\u{eacb}"
    case britishPound = "\u{eaca}"
    case browser = "\u{eac9}"
    case brush = "\u{eacc}"
    case bug = "\u{eacf}"
    case bullhorn = "\u{eacd}"
    case calculator = "\u{eace}"
    case calendar = "\u{ead4}"
    case cameraSlr = "\u{ead2}"
    case caretBottom = "\u{ead0}"
    case caretLeft = "\u{ead1}"
    case caretRight = "\u{ead3}"
    case caretTop = "\u{ead5}"
    case cart = "\u{ead8}"
    case chat = "\u{ead6}"
    case check = "\u{ead7}"
    case chevronBottom = "\u{eadd}"
    case chevronLeft = "\u{eada}"
    case chevronRight = "\u{eadb}"
    case chevronTop = "\u{eadc}"
    case circleCheck = "\u{ead9}"
    case circleX = "\u{eadf}"
    case clipboard = "\u{eade}"
    case clock = "\u{eaf2}"
    case cloud = "\u{eae2}"
    case cloudDownload = "\u{eae0}"
    case cloudUpload = "\u{eae1}"
    case cloudy = "\u{eae3}"
    case code = "\u{eae4}"
    case cog = "\u{eae5}"
    case collapseDown = "\u{eae6}"
    case collapseLeft = "\u{eae9}"
    case collapseRight = "\u{eae7}"
    case collapseUp = "\u{eae8}"
    case command = "\u{eaea}"
    case commentSquare = "\u{eaeb}"
    case compass = "\u{eaec}"
    case contrast = "\u{eaee}"
    case copywriting = "\u{eaed}"
    case creditCard = "\u{eaf1}"
    case crop = "\u{eaf0}"
    case dashboard = "\u{eaef}"
    case dataTransferDownload = "\u{eaf5}"
    case dataTransferUpload = "\u{eaf4}"
    case delete = "\u{eaf3}"
    case dial = "\u{eaf8}"
    case document = "\u{eaf7}"
    case dollar = "\u{eaf6}"
    case doubleQuoteSansLeft = "\u{eaf9}"
    case doubleQuoteSansRight = "\u{eafc}"
    case doubleQuoteSerifLeft = "\u{eafb}"
    case doubleQuoteSerifRight = "\u{eafa}"
    case droplet = "\u{eafd}"
    case eject = "\u{eafe}"
    case elevator = "\u{eb01}"
    case ellipses = "\u{eb00}"
    case envelopeClosed = "\u{eaff}"
    case envelopeOpen = "\u{eb03}"
    case euro = "\u{eb05}"
    case excerpt = "\u{eb02}"
    case expandDown = "\u{eb04}"
    case expandLeft = "\u{eb07}"
    case expandRight = "\u{eb06}"
    case expandUp = "\u{eb09}"
    case externalLink = "\u{eb0a}"
    case eye = "\u{eb08}"
    case eyedropper = "\u{eb0d}"
    case file = "\u{eb0b}"
    case fire = "\u{eb0c}"
    case flag = "\u{eb0e}"
    case flash = "\u{eb12}"
    case folder = "\u{eb0f}"
    case fork = "\u{eb13}"
    case fullscreenEnter = "\u{eb11}"
    case fullscreenExit = "\u{eb10}"
    case globe = "\u{eb14}"
    case graph = "\u{eb15}"
    case gridFourUp = "\u{eb17}"
    case gridThreeUp = "\u{eb18}"
    case gridTwoUp = "\u{eb16}"
    case hardDrive = "\u{eb19}"
    case header = "\u{eb1c}"
    case headphones = "\u{eb1b}"
    case heart = "\u{eb1a}"
    case home = "\u{eb21}"
    case image = "\u{eb1e}"
    case inbox = "\u{eb1d}"
    case infinity = "\u{eb1f}"
    case info = "\u{eb20}"
    case italic = "\u{eb22}"
    case justifyCenter = "\u{eb24}"
    case justifyLeft = "\u{eb26}"
    case justifyRight = "\u{eb23}"
    case key = "\u{eb25}"
    case laptop = "\u{eb2a}"
    case layers = "\u{eb27}"
    case lightbulb = "\u{eb28}"
    case linkBroken = "\u{eb29}"
    case linkIntact = "\u{eb2b}"
    case list = "\u{eb2f}"
    case listRich = "\u{eb2c}"
    case location = "\u{eb2d}"
    case lockLocked = "\u{eb2e}"
    case lockUnlocked = "\u{eb31}"
    case loop = "\u{eb33}"
    case loopCircular = "\u{eb30}"
    case loopSquare = "\u{eb32}"
    case magnifyingGlass = "\u{eb35}"
    case map = "\u{eb37}"
    case mapMarker = "\u{eb36}"
    case mediaPause = "\u{eb34}"
    case mediaPlay = "\u{eb49}"
    case mediaRecord = "\u{eb39}"
    case mediaSkipBackward = "\u{eb38}"
    case mediaSkipForward = "\u{eb3c}"
    case mediaStepBackward = "\u{eb3a}"
    case mediaStepForward = "\u{eb3b}"
    case mediaStop = "\u{eb44}"
    case medicalCross = "\u{eb3e}"
    case menu = "\u{eb3d}"
    case microphone = "\u{eb3f}"
    case minus = "\u{eb40}"
    case monitor = "\u{eb42}"
    case moon = "\u{eb41}"
    case move = "\u{eb45}"
    case musicalNote = "\u{eb43}"
    case paperclip = "\u{eb4a}"
    case pencil = "\u{eb48}"
    case people = "\u{eb46}"
    case person = "\u{eb4b}"
    case phone = "\u{eb4c}"
    case pieChart = "\u{eb47}"
    case pin = "\u{eb4d}"
    case playCircle = "\u{eb4e}"
    case plus = "\u{eb4f}"
    case powerStandby = "\u{eb50}"
    case print = "\u{eb52}"
    case project = "\u{eb51}"
    case pulse = "\u{eb53}"
    case puzzlePiece = "\u{eb54}"
    case questionMark = "\u{eb55}"
    case rain = "\u{eb57}"
    case random = "\u{eb56}"
    case reload = "\u{eb59}"
    case resizeBoth = "\u{eb5a}"
    case resizeHeight = "\u{eb5c}"
    case resizeWidth = "\u{eb58}"
    case rss = "\u{eb5e}"
    case rssAlt = "\u{eb5b}"
    case script = "\u{eb5d}"
    case share = "\u{eb62}"
    case shareBoxed = "\u{eb5f}"
    case shield = "\u{eb6e}"
    case signal = "\u{eb7d}"
    case signpost = "\u{eb61}"
    case sortAscending = "\u{eb60}"
    case sortDescending = "\u{eb63}"
    case spreadsheet = "\u{eb64}"
    case star = "\u{eb65}"
    case sun = "\u{eb66}"
    case tablet = "\u{eb67}"
    case tag = "\u{eb68}"
    case tags = "\u{eb6a}"
    case target = "\u{eb6c}"
    case task = "\u{eb69}"
    case terminal = "\u{eb6b}"
    case text = "\u{eb6f}"
    case thumbDown = "\u{eb6d}"
    case thumbUp = "\u{eb70}"
    case timer = "\u{eb71}"
    case transfer = "\u{eb72}"
    case trash = "\u{eb75}"
    case underline = "\u{eb74}"
    case verticalAlignBottom = "\u{eb73}"
    case verticalAlignCenter = "\u{eb76}"
    case verticalAlignTop = "\u{eb78}"
    case video = "\u{eb77}"
    case volumeHigh = "\u{eb79}"
    case volumeLow = "\u{eb7b}"
    case volumeOff = "\u{eb7a}"
    case warning = "\u{eb7c}"
    case wifi = "\u{eb7e}"
    case wrench = "\u{eb7f}"
    case x = "\u{eb81}"
    case yen = "\u{eb83}"
    case zoomIn = "\u{eb80}"
    case zoomOut = "\u{eb82}"
}
